# Template for Local Development Configuration
# Copy this file to application-local.yml and fill in your PayPal credentials
# Use with: --spring.profiles.active=local

# PayPal Configuration (Sandbox for Testing)
# 1. Go to https://developer.paypal.com/
# 2. Create a sandbox application
# 3. Copy your Client ID and Client Secret below
paypal:
  client-id: AccJFos4AqS4-gjxPDrVygjiZZZuhVKZ_zx4eiI446UoAC2rzUvVp_g2DsJDMIOyZurVRmN6YYcbGsT3
  client-secret: ENQZd4ZarqPKYmLHSETSX0iGweJEPOrD8ABe8VTcka4WZ-IJ_yYPHgfUKbLivyP4-DUzVX87w-32WhYQ
  mode: sandbox  # Use 'live' for production
  base-url: https://api.sandbox.paypal.com
  return-url: http://localhost:8888/api/payments/paypal/success
  cancel-url: http://localhost:8888/api/payments/paypal/cancel

# Database configuration for local development
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration for local development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema on each restart for testing
    show-sql: true  # Show SQL queries in local development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# API Documentation - enabled for local development only
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.example.demo: DEBUG
    com.paypal: DEBUG