# Simple development configuration
server:
  port: 8888

spring:
  application:
    name: ticket-booking-system

  # Database configuration - supports environment variables
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  # JPA configuration - development friendly
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Auto-import data after DDL creation
        hbm2ddl.import_files: import.sql

# Basic management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Development logging
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.example.demo: ${LOGGING_LEVEL_COM_EXAMPLE:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_SQL_PARAMS:TRACE}

# PayPal configuration
paypal:
  client:
    id: ${PAYPAL_CLIENT_ID:your_paypal_client_id}
    secret: ${PAYPAL_CLIENT_SECRET:your_paypal_client_secret}
  mode: ${PAYPAL_MODE:sandbox}
  currency: USD

# Stripe configuration
stripe:
  secret-key: ${STRIPE_SECRET_KEY:your_stripe_secret_key}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:your_stripe_publishable_key}

# JWT configuration
jwt:
  secret-key: ${JWT_SECRET_KEY:ZGVmYXVsdFNlY3JldEtleUZvckRldmVsb3BtZW50T25seU11c3RCZUF0TGVhc3QyNTZCaXRzTG9uZw==}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:your_stripe_webhook_secret}

# CORS configuration
cors:
  allowed-origins:
    - http://localhost:3001
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

